import type { Product } from "@/types";

export const mockProducts: Product[] = [
  {
    id: 97,
    title: "Rolex Datejust",
    description:
      "The Rolex Datejust is an iconic and versatile timepiece with a date window. Known for its timeless design and reliability, it's a symbol of Rolex's watchmaking excellence.",
    category: "mens-watches",
    price: 10999.99,
    discountPercentage: 3.73,
    rating: 3.66,
    stock: 86,
    tags: ["watches", "luxury watches"],
    brand: "Rolex",
    sku: "MEN-ROL-ROL-097",
    weight: 4,
    dimensions: {
      width: 23.11,
      height: 19.97,
      depth: 27.04,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast shipping!",
        date: new Date("2025-04-30T09:41:02.053Z"),
        reviewerName: "Alice Smith",
        reviewerEmail: "alice.smith@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very pleased!",
        date: new Date("2025-04-30T09:41:02.053Z"),
        reviewerName: "Abigail Rivera",
        reviewerEmail: "abigail.rivera@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Waste of money!",
        date: new Date("2025-04-30T09:41:02.053Z"),
        reviewerName: "Daniel Cook",
        reviewerEmail: "daniel.cook@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: new Date("2025-04-30T09:41:02.053Z"),
      updatedAt: new Date("2025-04-30T09:41:02.053Z"),
      barcode: "8893788734644",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/thumbnail.webp",
  },
  {
    id: 93,
    title: "Brown Leather Belt Watch",
    description:
      "The Brown Leather Belt Watch is a stylish timepiece with a classic design. Featuring a genuine leather strap and a sleek dial, it adds a touch of sophistication to your look.",
    category: "mens-watches",
    price: 89.99,
    discountPercentage: 5.99,
    rating: 4.19,
    stock: 32,
    tags: ["watches", "leather watches"],
    brand: "Fashion Timepieces",
    sku: "MEN-FAS-BRO-093",
    weight: 10,
    dimensions: {
      width: 16.65,
      height: 6.15,
      depth: 20.18,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 1,
        comment: "Very unhappy with my purchase!",
        date: new Date("2025-04-30T09:41:02.053Z"),
        reviewerName: "James Garcia",
        reviewerEmail: "james.garcia@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: new Date("2025-04-30T09:41:02.053Z"),
        reviewerName: "Avery Barnes",
        reviewerEmail: "avery.barnes@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: new Date("2025-04-30T09:41:02.053Z"),
        reviewerName: "David Martinez",
        reviewerEmail: "david.martinez@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 7,
    meta: {
      createdAt: new Date("2025-04-30T09:41:02.053Z"),
      updatedAt: new Date("2025-04-30T09:41:02.053Z"),
      barcode: "4027206714862",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/1.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/2.webp",
      "https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/thumbnail.webp",
  },
];
